"""
Vessels Dynamic Canvas System

Voice-first UI where conversation drives everything. Visual content appears
contextually - generated by AI agents in response to what's being discussed.
Movie-style subtitles overlay the content to show who's speaking.

The model:
- Live humans have proxy agents representing them in roles
- Proxies converse with other agents (human proxies or entity agents)
- Entity agents represent non-human things: plants, machines, places, biomes
- Humans can direct their proxy or barge in directly
- All participants react to each other, the canvas, and context
"""

import asyncio
import json
from datetime import datetime, timezone
from enum import Enum
from typing import Any, Optional, Callable, List, Dict
from dataclasses import dataclass, field
from pydantic import BaseModel, Field

from python.helpers.graph_store import GraphStore, get_graph_store
from python.helpers.print_style import PrintStyle
from python.helpers import guids


# =============================================================================
# Enums and Constants
# =============================================================================

class ParticipantType(str, Enum):
    """Types of conversation participants."""
    HUMAN_PROXY = "human_proxy"      # Represents a human in a role
    ENTITY_AGENT = "entity_agent"    # Represents non-human entity
    HUMAN_DIRECT = "human_direct"    # Human speaking directly (barge-in)


class EntityKind(str, Enum):
    """Kinds of entities that can have agents."""
    PLANT = "plant"           # Trees, crops, gardens
    CREATURE = "creature"     # Animals, insects, microbes
    MACHINE = "machine"       # Equipment, vehicles, systems
    PLACE = "place"           # Locations, buildings, regions
    BIOME = "biome"           # Ecosystems, watersheds, soil
    RESOURCE = "resource"     # Food, water, materials
    PROCESS = "process"       # Workflows, cycles, patterns
    COLLECTIVE = "collective" # Groups, communities, networks


class CanvasContentType(str, Enum):
    """Types of content that can appear on the canvas."""
    MAP = "map"                     # Geographic visualization
    CALENDAR = "calendar"           # Time/scheduling view
    VISUALIZATION = "visualization" # Data/charts/graphs
    GALLERY = "gallery"             # Photos/images
    APPLET = "applet"               # Interactive widget
    AMBIENT = "ambient"             # Background/mood imagery
    ENTITY_VIEW = "entity_view"     # Entity status/details
    RELATIONSHIP = "relationship"   # Connection visualization


class EmotionalState(str, Enum):
    """Emotional states detected from voice (Hume.ai integration)."""
    NEUTRAL = "neutral"
    EXCITED = "excited"
    STRESSED = "stressed"
    CONFUSED = "confused"
    FRUSTRATED = "frustrated"
    SATISFIED = "satisfied"
    CURIOUS = "curious"
    URGENT = "urgent"


# =============================================================================
# Participant Models
# =============================================================================

@dataclass
class SpeakerStyle:
    """Visual styling for a speaker's subtitles."""
    color: str = "#ffffff"
    background: str = "rgba(0,0,0,0.7)"
    font_weight: str = "normal"
    font_style: str = "normal"
    icon: str = ""
    position: str = "bottom"  # bottom, top, left, right

    def to_dict(self) -> dict:
        return {
            "color": self.color,
            "background": self.background,
            "fontWeight": self.font_weight,
            "fontStyle": self.font_style,
            "icon": self.icon,
            "position": self.position,
        }


@dataclass
class Participant:
    """Base class for all conversation participants."""
    id: str
    name: str
    participant_type: ParticipantType
    style: SpeakerStyle = field(default_factory=SpeakerStyle)
    voice_id: str = ""  # For TTS voice selection
    personality: str = ""  # Brief personality description
    knowledge_areas: List[str] = field(default_factory=list)
    active: bool = True

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "name": self.name,
            "type": self.participant_type.value,
            "style": self.style.to_dict(),
            "voiceId": self.voice_id,
            "personality": self.personality,
            "knowledgeAreas": self.knowledge_areas,
            "active": self.active,
        }

    @classmethod
    def from_dict(cls, data: dict) -> "Participant":
        style_data = data.get("style", {})
        return cls(
            id=data["id"],
            name=data["name"],
            participant_type=ParticipantType(data.get("type", "entity_agent")),
            style=SpeakerStyle(**style_data) if style_data else SpeakerStyle(),
            voice_id=data.get("voiceId", ""),
            personality=data.get("personality", ""),
            knowledge_areas=data.get("knowledgeAreas", []),
            active=data.get("active", True),
        )


@dataclass
class HumanProxy(Participant):
    """Represents a human in a specific role."""
    human_id: str = ""  # Links to the actual human
    role: str = ""      # The role they're playing (gardener, coordinator, etc.)
    can_barge_in: bool = True

    def __post_init__(self):
        self.participant_type = ParticipantType.HUMAN_PROXY
        if not self.style.color:
            self.style.color = "#4ade80"  # Green for humans

    def to_dict(self) -> dict:
        base = super().to_dict()
        base.update({
            "humanId": self.human_id,
            "role": self.role,
            "canBargeIn": self.can_barge_in,
        })
        return base


@dataclass
class EntityAgent(Participant):
    """Represents a non-human entity (plant, machine, place, etc.)."""
    entity_kind: EntityKind = EntityKind.PLANT
    entity_data: Dict[str, Any] = field(default_factory=dict)
    location: Optional[Dict[str, float]] = None  # lat, lng
    status: str = "active"
    relationships: List[str] = field(default_factory=list)  # IDs of related entities

    def __post_init__(self):
        self.participant_type = ParticipantType.ENTITY_AGENT
        # Set default colors by entity kind
        kind_colors = {
            EntityKind.PLANT: "#22c55e",      # Green
            EntityKind.CREATURE: "#f59e0b",   # Amber
            EntityKind.MACHINE: "#6366f1",    # Indigo
            EntityKind.PLACE: "#8b5cf6",      # Purple
            EntityKind.BIOME: "#14b8a6",      # Teal
            EntityKind.RESOURCE: "#f97316",   # Orange
            EntityKind.PROCESS: "#06b6d4",    # Cyan
            EntityKind.COLLECTIVE: "#ec4899", # Pink
        }
        if not self.style.color:
            self.style.color = kind_colors.get(self.entity_kind, "#ffffff")

    def to_dict(self) -> dict:
        base = super().to_dict()
        base.update({
            "entityKind": self.entity_kind.value,
            "entityData": self.entity_data,
            "location": self.location,
            "status": self.status,
            "relationships": self.relationships,
        })
        return base


# =============================================================================
# Canvas Content Models
# =============================================================================

@dataclass
class CanvasElement:
    """A visual element on the canvas."""
    id: str
    content_type: CanvasContentType
    content: Dict[str, Any]  # Type-specific content data
    priority: int = 0        # Higher = more prominent
    duration: Optional[float] = None  # Auto-dismiss after seconds
    triggered_by: str = ""   # Participant ID that triggered this
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "contentType": self.content_type.value,
            "content": self.content,
            "priority": self.priority,
            "duration": self.duration,
            "triggeredBy": self.triggered_by,
            "createdAt": self.created_at.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "CanvasElement":
        return cls(
            id=data["id"],
            content_type=CanvasContentType(data["contentType"]),
            content=data["content"],
            priority=data.get("priority", 0),
            duration=data.get("duration"),
            triggered_by=data.get("triggeredBy", ""),
            created_at=datetime.fromisoformat(data["createdAt"]) if "createdAt" in data else datetime.now(timezone.utc),
        )


@dataclass
class Subtitle:
    """A subtitle overlay showing who's speaking."""
    id: str
    participant_id: str
    participant_name: str
    text: str
    style: SpeakerStyle
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    duration: float = 5.0  # Seconds to display
    is_streaming: bool = False

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "participantId": self.participant_id,
            "participantName": self.participant_name,
            "text": self.text,
            "style": self.style.to_dict(),
            "timestamp": self.timestamp.isoformat(),
            "duration": self.duration,
            "isStreaming": self.is_streaming,
        }


# =============================================================================
# Conversation Room
# =============================================================================

@dataclass
class ConversationGist:
    """Extracted understanding of the current conversation state."""
    topics: List[str] = field(default_factory=list)
    intent: str = ""  # What participants are trying to accomplish
    entities_discussed: List[str] = field(default_factory=list)
    locations_mentioned: List[Dict[str, Any]] = field(default_factory=list)
    time_references: List[str] = field(default_factory=list)
    emotional_tone: EmotionalState = EmotionalState.NEUTRAL
    suggested_content: List[CanvasContentType] = field(default_factory=list)
    action_items: List[str] = field(default_factory=list)
    questions_pending: List[str] = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "topics": self.topics,
            "intent": self.intent,
            "entitiesDiscussed": self.entities_discussed,
            "locationsMentioned": self.locations_mentioned,
            "timeReferences": self.time_references,
            "emotionalTone": self.emotional_tone.value,
            "suggestedContent": [c.value for c in self.suggested_content],
            "actionItems": self.action_items,
            "questionsPending": self.questions_pending,
        }


@dataclass
class ConversationTurn:
    """A single turn in the conversation."""
    id: str
    participant_id: str
    content: str
    timestamp: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    is_direction: bool = False  # True if human directing their proxy
    emotional_state: EmotionalState = EmotionalState.NEUTRAL
    references_canvas: bool = False  # True if referring to current canvas content

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "participantId": self.participant_id,
            "content": self.content,
            "timestamp": self.timestamp.isoformat(),
            "isDirection": self.is_direction,
            "emotionalState": self.emotional_state.value,
            "referencesCanvas": self.references_canvas,
        }


class ConversationRoom:
    """
    A multi-agent dialogue container.

    Manages participants, tracks conversation flow, maintains canvas state,
    and coordinates turn-taking between agents.
    """

    def __init__(self, room_id: str, name: str = ""):
        self.id = room_id
        self.name = name or f"Room {room_id[:8]}"
        self.participants: Dict[str, Participant] = {}
        self.turns: List[ConversationTurn] = []
        self.canvas_elements: Dict[str, CanvasElement] = {}
        self.active_subtitles: List[Subtitle] = []
        self.gist: ConversationGist = ConversationGist()
        self.created_at = datetime.now(timezone.utc)
        self.last_activity = datetime.now(timezone.utc)

        # Callbacks for real-time updates
        self._canvas_listeners: List[Callable] = []
        self._subtitle_listeners: List[Callable] = []
        self._turn_listeners: List[Callable] = []

        # Human intervention state
        self._human_speaking: Optional[str] = None  # Human ID if barging in
        self._pending_directions: Dict[str, List[str]] = {}  # proxy_id -> directions

    # =========================================================================
    # Participant Management
    # =========================================================================

    def add_participant(self, participant: Participant) -> None:
        """Add a participant to the room."""
        self.participants[participant.id] = participant
        self._notify_turn({"type": "participant_joined", "participant": participant.to_dict()})

    def remove_participant(self, participant_id: str) -> None:
        """Remove a participant from the room."""
        if participant_id in self.participants:
            participant = self.participants.pop(participant_id)
            self._notify_turn({"type": "participant_left", "participant": participant.to_dict()})

    def get_participant(self, participant_id: str) -> Optional[Participant]:
        """Get a participant by ID."""
        return self.participants.get(participant_id)

    def get_active_participants(self) -> List[Participant]:
        """Get all active participants."""
        return [p for p in self.participants.values() if p.active]

    def get_human_proxies(self) -> List[HumanProxy]:
        """Get all human proxy participants."""
        return [p for p in self.participants.values()
                if isinstance(p, HumanProxy)]

    def get_entity_agents(self) -> List[EntityAgent]:
        """Get all entity agent participants."""
        return [p for p in self.participants.values()
                if isinstance(p, EntityAgent)]

    # =========================================================================
    # Conversation Flow
    # =========================================================================

    def add_turn(self, participant_id: str, content: str,
                 is_direction: bool = False,
                 emotional_state: EmotionalState = EmotionalState.NEUTRAL,
                 references_canvas: bool = False) -> ConversationTurn:
        """Add a new turn to the conversation."""
        turn = ConversationTurn(
            id=guids.generate_id(8),
            participant_id=participant_id,
            content=content,
            is_direction=is_direction,
            emotional_state=emotional_state,
            references_canvas=references_canvas,
        )
        self.turns.append(turn)
        self.last_activity = datetime.now(timezone.utc)

        # Create subtitle for this turn
        participant = self.get_participant(participant_id)
        if participant:
            self._add_subtitle(participant, content)

        # Notify listeners
        self._notify_turn({"type": "new_turn", "turn": turn.to_dict()})

        return turn

    def human_directs_proxy(self, human_id: str, proxy_id: str, direction: str) -> None:
        """Human gives direction to their proxy agent."""
        proxy = self.get_participant(proxy_id)
        if not proxy or not isinstance(proxy, HumanProxy):
            return
        if proxy.human_id != human_id:
            return  # Can only direct own proxy

        # Queue the direction
        if proxy_id not in self._pending_directions:
            self._pending_directions[proxy_id] = []
        self._pending_directions[proxy_id].append(direction)

        # Record as a direction turn (not shown as subtitle)
        self.add_turn(proxy_id, f"[Direction: {direction}]", is_direction=True)

    def human_barge_in(self, human_id: str, content: str) -> ConversationTurn:
        """Human speaks directly, interrupting the conversation."""
        self._human_speaking = human_id

        # Create a temporary direct participant entry
        direct_id = f"human_direct_{human_id}"
        if direct_id not in self.participants:
            # Find their proxy to get name
            proxy = next((p for p in self.get_human_proxies()
                         if p.human_id == human_id), None)
            name = proxy.name.replace(" (proxy)", "") if proxy else "Human"

            direct_participant = Participant(
                id=direct_id,
                name=f"{name} (direct)",
                participant_type=ParticipantType.HUMAN_DIRECT,
                style=SpeakerStyle(
                    color="#fbbf24",  # Gold for direct human
                    font_weight="bold",
                    icon="👤",
                ),
            )
            self.participants[direct_id] = direct_participant

        turn = self.add_turn(direct_id, content)
        self._human_speaking = None
        return turn

    def get_pending_directions(self, proxy_id: str) -> List[str]:
        """Get and clear pending directions for a proxy."""
        directions = self._pending_directions.pop(proxy_id, [])
        return directions

    def get_recent_turns(self, count: int = 10) -> List[ConversationTurn]:
        """Get the most recent turns."""
        return self.turns[-count:] if self.turns else []

    def get_conversation_text(self, count: int = 20) -> str:
        """Get recent conversation as formatted text."""
        lines = []
        for turn in self.get_recent_turns(count):
            if turn.is_direction:
                continue  # Skip direction turns
            participant = self.get_participant(turn.participant_id)
            name = participant.name if participant else "Unknown"
            lines.append(f"{name}: {turn.content}")
        return "\n".join(lines)

    # =========================================================================
    # Canvas Management
    # =========================================================================

    def set_canvas(self, element: CanvasElement) -> None:
        """Set or update a canvas element."""
        self.canvas_elements[element.id] = element
        self._notify_canvas({"type": "canvas_update", "element": element.to_dict()})

    def clear_canvas(self, element_id: Optional[str] = None) -> None:
        """Clear canvas element(s)."""
        if element_id:
            if element_id in self.canvas_elements:
                del self.canvas_elements[element_id]
                self._notify_canvas({"type": "canvas_clear", "elementId": element_id})
        else:
            self.canvas_elements.clear()
            self._notify_canvas({"type": "canvas_clear_all"})

    def get_canvas_state(self) -> List[Dict]:
        """Get current canvas state."""
        # Sort by priority (highest first)
        elements = sorted(
            self.canvas_elements.values(),
            key=lambda e: e.priority,
            reverse=True
        )
        return [e.to_dict() for e in elements]

    def generate_map(self, title: str, locations: List[Dict],
                     triggered_by: str = "", **kwargs) -> CanvasElement:
        """Generate a map canvas element."""
        element = CanvasElement(
            id=guids.generate_id(8),
            content_type=CanvasContentType.MAP,
            content={
                "title": title,
                "locations": locations,
                "center": kwargs.get("center"),
                "zoom": kwargs.get("zoom", 12),
                "routes": kwargs.get("routes", []),
                **kwargs,
            },
            priority=kwargs.get("priority", 5),
            triggered_by=triggered_by,
        )
        self.set_canvas(element)
        return element

    def generate_calendar(self, title: str, events: List[Dict],
                          triggered_by: str = "", **kwargs) -> CanvasElement:
        """Generate a calendar canvas element."""
        element = CanvasElement(
            id=guids.generate_id(8),
            content_type=CanvasContentType.CALENDAR,
            content={
                "title": title,
                "events": events,
                "view": kwargs.get("view", "week"),
                "highlighted": kwargs.get("highlighted", []),
                **kwargs,
            },
            priority=kwargs.get("priority", 5),
            triggered_by=triggered_by,
        )
        self.set_canvas(element)
        return element

    def generate_visualization(self, title: str, data: Dict,
                               chart_type: str = "bar",
                               triggered_by: str = "", **kwargs) -> CanvasElement:
        """Generate a data visualization canvas element."""
        element = CanvasElement(
            id=guids.generate_id(8),
            content_type=CanvasContentType.VISUALIZATION,
            content={
                "title": title,
                "data": data,
                "chartType": chart_type,
                "animated": kwargs.get("animated", True),
                **kwargs,
            },
            priority=kwargs.get("priority", 5),
            triggered_by=triggered_by,
        )
        self.set_canvas(element)
        return element

    def generate_gallery(self, title: str, images: List[Dict],
                         triggered_by: str = "", **kwargs) -> CanvasElement:
        """Generate a photo gallery canvas element."""
        element = CanvasElement(
            id=guids.generate_id(8),
            content_type=CanvasContentType.GALLERY,
            content={
                "title": title,
                "images": images,
                "layout": kwargs.get("layout", "grid"),
                **kwargs,
            },
            priority=kwargs.get("priority", 5),
            triggered_by=triggered_by,
        )
        self.set_canvas(element)
        return element

    def generate_entity_view(self, entity: EntityAgent,
                             triggered_by: str = "", **kwargs) -> CanvasElement:
        """Generate an entity detail view."""
        element = CanvasElement(
            id=guids.generate_id(8),
            content_type=CanvasContentType.ENTITY_VIEW,
            content={
                "entity": entity.to_dict(),
                "showRelationships": kwargs.get("showRelationships", True),
                "showHistory": kwargs.get("showHistory", False),
                **kwargs,
            },
            priority=kwargs.get("priority", 5),
            triggered_by=triggered_by,
        )
        self.set_canvas(element)
        return element

    def generate_ambient(self, mood: str, imagery: Dict,
                         triggered_by: str = "", **kwargs) -> CanvasElement:
        """Generate ambient background imagery."""
        element = CanvasElement(
            id=guids.generate_id(8),
            content_type=CanvasContentType.AMBIENT,
            content={
                "mood": mood,
                "imagery": imagery,
                "animation": kwargs.get("animation", "gentle"),
                **kwargs,
            },
            priority=kwargs.get("priority", 0),  # Lowest priority (background)
            triggered_by=triggered_by,
        )
        self.set_canvas(element)
        return element

    # =========================================================================
    # Subtitle Management
    # =========================================================================

    def _add_subtitle(self, participant: Participant, text: str,
                      duration: float = 5.0, is_streaming: bool = False) -> Subtitle:
        """Add a subtitle overlay."""
        subtitle = Subtitle(
            id=guids.generate_id(8),
            participant_id=participant.id,
            participant_name=participant.name,
            text=text,
            style=participant.style,
            duration=duration,
            is_streaming=is_streaming,
        )
        self.active_subtitles.append(subtitle)
        self._notify_subtitle({"type": "subtitle_add", "subtitle": subtitle.to_dict()})

        # Schedule removal (in real implementation, handle async)
        if not is_streaming:
            asyncio.get_event_loop().call_later(
                duration,
                lambda: self._remove_subtitle(subtitle.id)
            )

        return subtitle

    def _remove_subtitle(self, subtitle_id: str) -> None:
        """Remove a subtitle."""
        self.active_subtitles = [s for s in self.active_subtitles if s.id != subtitle_id]
        self._notify_subtitle({"type": "subtitle_remove", "subtitleId": subtitle_id})

    def update_streaming_subtitle(self, subtitle_id: str, text: str) -> None:
        """Update text of a streaming subtitle."""
        for subtitle in self.active_subtitles:
            if subtitle.id == subtitle_id:
                subtitle.text = text
                self._notify_subtitle({
                    "type": "subtitle_update",
                    "subtitleId": subtitle_id,
                    "text": text,
                })
                break

    def finish_streaming_subtitle(self, subtitle_id: str, final_text: str,
                                   duration: float = 5.0) -> None:
        """Finish a streaming subtitle and schedule removal."""
        for subtitle in self.active_subtitles:
            if subtitle.id == subtitle_id:
                subtitle.text = final_text
                subtitle.is_streaming = False
                subtitle.duration = duration
                self._notify_subtitle({
                    "type": "subtitle_finish",
                    "subtitleId": subtitle_id,
                    "text": final_text,
                })
                asyncio.get_event_loop().call_later(
                    duration,
                    lambda: self._remove_subtitle(subtitle_id)
                )
                break

    def get_active_subtitles(self) -> List[Dict]:
        """Get currently active subtitles."""
        return [s.to_dict() for s in self.active_subtitles]

    # =========================================================================
    # Gist Analysis
    # =========================================================================

    def update_gist(self, gist: ConversationGist) -> None:
        """Update the conversation gist."""
        self.gist = gist
        self._notify_turn({"type": "gist_update", "gist": gist.to_dict()})

    def get_gist(self) -> ConversationGist:
        """Get current conversation gist."""
        return self.gist

    # =========================================================================
    # Event Listeners
    # =========================================================================

    def on_canvas_update(self, callback: Callable) -> None:
        """Register a canvas update listener."""
        self._canvas_listeners.append(callback)

    def on_subtitle_update(self, callback: Callable) -> None:
        """Register a subtitle update listener."""
        self._subtitle_listeners.append(callback)

    def on_turn(self, callback: Callable) -> None:
        """Register a turn listener."""
        self._turn_listeners.append(callback)

    def _notify_canvas(self, event: Dict) -> None:
        """Notify canvas listeners."""
        for listener in self._canvas_listeners:
            try:
                listener(event)
            except Exception as e:
                PrintStyle.error(f"Canvas listener error: {e}")

    def _notify_subtitle(self, event: Dict) -> None:
        """Notify subtitle listeners."""
        for listener in self._subtitle_listeners:
            try:
                listener(event)
            except Exception as e:
                PrintStyle.error(f"Subtitle listener error: {e}")

    def _notify_turn(self, event: Dict) -> None:
        """Notify turn listeners."""
        for listener in self._turn_listeners:
            try:
                listener(event)
            except Exception as e:
                PrintStyle.error(f"Turn listener error: {e}")

    # =========================================================================
    # Serialization
    # =========================================================================

    def to_dict(self) -> dict:
        """Serialize the room state."""
        return {
            "id": self.id,
            "name": self.name,
            "participants": {k: v.to_dict() for k, v in self.participants.items()},
            "turns": [t.to_dict() for t in self.turns],
            "canvasElements": {k: v.to_dict() for k, v in self.canvas_elements.items()},
            "activeSubtitles": [s.to_dict() for s in self.active_subtitles],
            "gist": self.gist.to_dict(),
            "createdAt": self.created_at.isoformat(),
            "lastActivity": self.last_activity.isoformat(),
        }

    @classmethod
    def from_dict(cls, data: dict) -> "ConversationRoom":
        """Deserialize a room from dict."""
        room = cls(room_id=data["id"], name=data.get("name", ""))

        # Restore participants
        for pid, pdata in data.get("participants", {}).items():
            ptype = ParticipantType(pdata.get("type", "entity_agent"))
            if ptype == ParticipantType.HUMAN_PROXY:
                room.participants[pid] = HumanProxy(
                    id=pdata["id"],
                    name=pdata["name"],
                    participant_type=ptype,
                    human_id=pdata.get("humanId", ""),
                    role=pdata.get("role", ""),
                )
            elif ptype == ParticipantType.ENTITY_AGENT:
                room.participants[pid] = EntityAgent(
                    id=pdata["id"],
                    name=pdata["name"],
                    participant_type=ptype,
                    entity_kind=EntityKind(pdata.get("entityKind", "plant")),
                    entity_data=pdata.get("entityData", {}),
                )
            else:
                room.participants[pid] = Participant.from_dict(pdata)

        # Restore turns
        for tdata in data.get("turns", []):
            turn = ConversationTurn(
                id=tdata["id"],
                participant_id=tdata["participantId"],
                content=tdata["content"],
                timestamp=datetime.fromisoformat(tdata["timestamp"]),
                is_direction=tdata.get("isDirection", False),
                emotional_state=EmotionalState(tdata.get("emotionalState", "neutral")),
            )
            room.turns.append(turn)

        # Restore canvas
        for eid, edata in data.get("canvasElements", {}).items():
            room.canvas_elements[eid] = CanvasElement.from_dict(edata)

        return room


# =============================================================================
# Room Manager (Singleton)
# =============================================================================

class RoomManager:
    """Manages all active conversation rooms."""

    _instance: Optional["RoomManager"] = None
    _lock = asyncio.Lock()

    def __init__(self):
        self.rooms: Dict[str, ConversationRoom] = {}
        self._graph_store: Optional[GraphStore] = None

    @classmethod
    async def get_instance(cls) -> "RoomManager":
        """Get the singleton instance."""
        async with cls._lock:
            if cls._instance is None:
                cls._instance = cls()
                cls._instance._graph_store = await get_graph_store()
            return cls._instance

    async def create_room(self, name: str = "") -> ConversationRoom:
        """Create a new conversation room."""
        room_id = guids.generate_id(12)
        room = ConversationRoom(room_id, name)
        self.rooms[room_id] = room
        await self._persist_room(room)
        return room

    async def get_room(self, room_id: str) -> Optional[ConversationRoom]:
        """Get a room by ID."""
        if room_id in self.rooms:
            return self.rooms[room_id]

        # Try to load from graph store
        return await self._load_room(room_id)

    async def get_or_create_room(self, room_id: str, name: str = "") -> ConversationRoom:
        """Get existing room or create new one."""
        room = await self.get_room(room_id)
        if not room:
            room = ConversationRoom(room_id, name)
            self.rooms[room_id] = room
            await self._persist_room(room)
        return room

    async def delete_room(self, room_id: str) -> bool:
        """Delete a room."""
        if room_id in self.rooms:
            del self.rooms[room_id]

        if self._graph_store:
            query = f"""
            MATCH (n:Episode) WHERE n.name = 'room_{room_id}'
            DETACH DELETE n
            """
            try:
                await self._graph_store._driver.execute_query(query)
                return True
            except Exception:
                return False
        return True

    async def _persist_room(self, room: ConversationRoom) -> None:
        """Persist room to graph store."""
        if not self._graph_store:
            return

        from graphiti_core.nodes import EpisodeType

        room_data = json.dumps(room.to_dict())
        await self._graph_store._graphiti.add_episode(
            name=f"room_{room.id}",
            episode_body=room_data,
            source=EpisodeType.json,
            reference_time=room.last_activity,
            group_id="conversation_rooms",
        )

    async def _load_room(self, room_id: str) -> Optional[ConversationRoom]:
        """Load room from graph store."""
        if not self._graph_store:
            return None

        query = f"""
        MATCH (n:Episode) WHERE n.name = 'room_{room_id}'
        RETURN n.content as content
        """
        try:
            result = await self._graph_store._driver.execute_query(query)
            if result and len(result) > 0:
                content = result[0].get("content", "{}")
                data = json.loads(content)
                room = ConversationRoom.from_dict(data)
                self.rooms[room_id] = room
                return room
        except Exception as e:
            PrintStyle.error(f"Failed to load room {room_id}: {e}")

        return None

    def get_all_rooms(self) -> List[ConversationRoom]:
        """Get all active rooms."""
        return list(self.rooms.values())


# =============================================================================
# Convenience Functions
# =============================================================================

async def get_room_manager() -> RoomManager:
    """Get the room manager singleton."""
    return await RoomManager.get_instance()


async def create_room(name: str = "") -> ConversationRoom:
    """Create a new conversation room."""
    manager = await get_room_manager()
    return await manager.create_room(name)


async def get_room(room_id: str) -> Optional[ConversationRoom]:
    """Get a room by ID."""
    manager = await get_room_manager()
    return await manager.get_room(room_id)
