# Vessels - Self-Instantiating Setup for Windows Docker Desktop
# PowerShell version for modern Windows users
#
# Run with: .\setup.ps1
# Or right-click and "Run with PowerShell"

$ErrorActionPreference = "Stop"

function Write-Banner {
    Write-Host ""
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host "   VESSELS - AI Agent Community Framework" -ForegroundColor Cyan
    Write-Host "=============================================" -ForegroundColor Cyan
    Write-Host ""
}

function Test-DockerRunning {
    try {
        $null = docker info 2>&1
        return $LASTEXITCODE -eq 0
    } catch {
        return $false
    }
}

function Get-ApiKeys {
    Write-Host ""
    Write-Host "=============================================" -ForegroundColor Yellow
    Write-Host "   API Key Configuration" -ForegroundColor Yellow
    Write-Host "=============================================" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "You need at least ONE LLM API key to run Vessels."
    Write-Host "Press Enter to skip if you don't have a key."
    Write-Host ""

    $openaiKey = Read-Host "OpenAI API Key (sk-...)"
    $anthropicKey = Read-Host "Anthropic API Key (sk-ant-...)"

    if ([string]::IsNullOrWhiteSpace($openaiKey) -and [string]::IsNullOrWhiteSpace($anthropicKey)) {
        Write-Host ""
        Write-Host "ERROR: You must provide at least one API key." -ForegroundColor Red
        Write-Host "Please get an API key from:"
        Write-Host "  - OpenAI: https://platform.openai.com/api-keys"
        Write-Host "  - Anthropic: https://console.anthropic.com/"
        Write-Host ""
        exit 1
    }

    # Configure Graphiti based on available keys
    if (-not [string]::IsNullOrWhiteSpace($openaiKey)) {
        $graphitiProvider = "openai"
        $graphitiModel = "gpt-4o-mini"
    } else {
        $graphitiProvider = "anthropic"
        $graphitiModel = "claude-3-haiku-20240307"
    }

    # Optional: Hume keys for voice personas
    Write-Host ""
    Write-Host "Optional: Hume AI keys for voice personas (press Enter to skip)"
    $humeApiKey = Read-Host "Hume API Key"
    $humeSecretKey = Read-Host "Hume Secret Key"

    return @{
        OpenAI = $openaiKey
        Anthropic = $anthropicKey
        GraphitiProvider = $graphitiProvider
        GraphitiModel = $graphitiModel
        HumeApiKey = $humeApiKey
        HumeSecretKey = $humeSecretKey
    }
}

function Write-EnvFile {
    param($Keys)

    $envContent = @"
# Vessels Configuration
# Generated by setup.ps1 on $(Get-Date)

# LLM API Keys
OPENAI_API_KEY=$($Keys.OpenAI)
ANTHROPIC_API_KEY=$($Keys.Anthropic)

# Graphiti Knowledge Graph LLM
GRAPHITI_LLM_PROVIDER=$($Keys.GraphitiProvider)
GRAPHITI_LLM_MODEL=$($Keys.GraphitiModel)

# Hume AI for voice personas (optional)
HUME_API_KEY=$($Keys.HumeApiKey)
HUME_SECRET_KEY=$($Keys.HumeSecretKey)
"@

    $envContent | Out-File -FilePath ".env" -Encoding utf8
    Write-Host "Configuration saved to .env" -ForegroundColor Green
}

function Start-Vessels {
    Write-Host ""
    Write-Host "=============================================" -ForegroundColor Green
    Write-Host "   Starting Vessels" -ForegroundColor Green
    Write-Host "=============================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "Building and starting Docker container..."
    Write-Host "This may take a few minutes on first run."
    Write-Host ""

    docker compose up -d --build

    if ($LASTEXITCODE -ne 0) {
        Write-Host ""
        Write-Host "ERROR: Failed to start Vessels." -ForegroundColor Red
        Write-Host "Check the Docker logs for details:"
        Write-Host "  docker compose logs"
        exit 1
    }
}

function Show-Success {
    Write-Host ""
    Write-Host "=============================================" -ForegroundColor Green
    Write-Host "   Vessels is starting!" -ForegroundColor Green
    Write-Host "=============================================" -ForegroundColor Green
    Write-Host ""
    Write-Host "The container is initializing. This may take 1-2 minutes."
    Write-Host ""
    Write-Host "Once ready, open your browser to:" -ForegroundColor Cyan
    Write-Host ""
    Write-Host "   http://localhost:8080" -ForegroundColor Yellow
    Write-Host ""
    Write-Host "Useful commands:"
    Write-Host "  View logs:    docker compose logs -f"
    Write-Host "  Stop:         docker compose down"
    Write-Host "  Restart:      docker compose restart"
    Write-Host ""

    $openBrowser = Read-Host "Open browser now? (Y/n)"
    if ($openBrowser -ne "n" -and $openBrowser -ne "N") {
        Start-Process "http://localhost:8080"
    }

    Write-Host ""
    Write-Host "Setup complete! Vessels is running in the background." -ForegroundColor Green
    Write-Host ""
}

# Main script
Write-Banner

# Check Docker
Write-Host "Checking Docker..." -ForegroundColor Cyan
if (-not (Test-DockerRunning)) {
    Write-Host "ERROR: Docker is not running." -ForegroundColor Red
    Write-Host "Please start Docker Desktop and try again."
    exit 1
}
Write-Host "Docker is running." -ForegroundColor Green

# Check for existing .env
if (Test-Path ".env") {
    Write-Host ""
    Write-Host "Found existing .env file." -ForegroundColor Yellow
    $overwrite = Read-Host "Do you want to reconfigure API keys? (y/N)"
    if ($overwrite -ne "y" -and $overwrite -ne "Y") {
        Write-Host "Using existing configuration."
        Start-Vessels
        Show-Success
        exit 0
    }
}

# Get keys and write config
$keys = Get-ApiKeys
Write-EnvFile -Keys $keys

# Start Vessels
Start-Vessels
Show-Success
