@echo off
REM Vessels - Self-Instantiating Setup for Windows Docker Desktop
REM This script prompts for API keys and starts Vessels automatically

setlocal enabledelayedexpansion

echo.
echo =============================================
echo    VESSELS - AI Agent Community Framework
echo =============================================
echo.

REM Check if Docker is running
docker info >nul 2>&1
if errorlevel 1 (
    echo ERROR: Docker is not running.
    echo Please start Docker Desktop and try again.
    pause
    exit /b 1
)

echo Docker is running. Proceeding with setup...
echo.

REM Check if .env already exists
if exist ".env" (
    echo Found existing .env file.
    set /p OVERWRITE="Do you want to reconfigure API keys? (y/N): "
    if /i not "!OVERWRITE!"=="y" (
        echo Using existing configuration.
        goto :start_vessels
    )
)

REM Prompt for API keys
echo.
echo =============================================
echo    API Key Configuration
echo =============================================
echo.
echo You need at least ONE LLM API key to run Vessels.
echo Press Enter to skip if you don't have a key.
echo.

set /p OPENAI_KEY="OpenAI API Key (sk-...): "
set /p ANTHROPIC_KEY="Anthropic API Key (sk-ant-...): "

REM Validate at least one key was provided
if "!OPENAI_KEY!"=="" if "!ANTHROPIC_KEY!"=="" (
    echo.
    echo ERROR: You must provide at least one API key.
    echo Please get an API key from:
    echo   - OpenAI: https://platform.openai.com/api-keys
    echo   - Anthropic: https://console.anthropic.com/
    echo.
    pause
    exit /b 1
)

REM Configure Graphiti LLM provider based on available keys
if not "!OPENAI_KEY!"=="" (
    set GRAPHITI_PROVIDER=openai
    set GRAPHITI_MODEL=gpt-4o-mini
) else (
    set GRAPHITI_PROVIDER=anthropic
    set GRAPHITI_MODEL=claude-3-haiku-20240307
)

REM Write .env file
echo.
echo Writing configuration to .env file...

(
echo # Vessels Configuration
echo # Generated by setup.bat on %date% %time%
echo.
echo # LLM API Keys
echo OPENAI_API_KEY=!OPENAI_KEY!
echo ANTHROPIC_API_KEY=!ANTHROPIC_KEY!
echo.
echo # Graphiti Knowledge Graph LLM
echo GRAPHITI_LLM_PROVIDER=!GRAPHITI_PROVIDER!
echo GRAPHITI_LLM_MODEL=!GRAPHITI_MODEL!
echo.
echo # Optional: Hume AI for voice personas
echo HUME_API_KEY=
echo HUME_SECRET_KEY=
) > .env

echo Configuration saved!

:start_vessels
echo.
echo =============================================
echo    Starting Vessels
echo =============================================
echo.
echo Building and starting Docker container...
echo This may take a few minutes on first run.
echo.

REM Build and start
docker compose up -d --build

if errorlevel 1 (
    echo.
    echo ERROR: Failed to start Vessels.
    echo Check the Docker logs for details:
    echo   docker compose logs
    pause
    exit /b 1
)

echo.
echo =============================================
echo    Vessels is starting!
echo =============================================
echo.
echo The container is initializing. This may take 1-2 minutes.
echo.
echo Once ready, open your browser to:
echo.
echo    http://localhost:8080
echo.
echo Useful commands:
echo   View logs:    docker compose logs -f
echo   Stop:         docker compose down
echo   Restart:      docker compose restart
echo.
echo Press any key to open the browser automatically...
pause >nul

start http://localhost:8080

echo.
echo Setup complete! Vessels is running in the background.
echo.
